### ISSUE TITLE
Crash during handshake capturing

### ISSUE THREAD

**Issue by koolaidxk1d** [phenotypic/WiFiCrackPy#20]
OS: Ventura 13.3
Machine: MBP M2
Python Version: 3.9.6 (non-brew)

Upon running the script, everything is fine up until capturing

```
Obtaining authorisation for location services (required for WiFi scanning)...

Received authorisation, continuing...

Scanning for networks...

+--------+----------------------+-------+------+---------+--------------------+
| Number |         Name         | BSSID | RSSI | Channel |      Security      |
+--------+----------------------+-------+------+---------+--------------------+
|   1    |       *CENSORED*        |  None | -36  |   149   | WPA2/WPA3 Personal |
|   2    |       *CENSORED*       |  None | -88  |    6    |   WPA2 Personal    |
|   3    |      *CENSORED*      |  None | -77  |    6    |   WPA2 Personal    |
|   4    |   *CENSORED*    |  None | -85  |    44   |  WPA2 Enterprise   |
|   5    |   *CENSORED*   |  None | -91  |    1    |   WPA2 Personal    |
|   6    |  *CENSORED*   |  None | -83  |    36   |   WPA2 Personal    |
|   7    |  *CENSORED*  |  None | -73  |    1    |   WPA2 Personal    |
|   8    |  *CENSORED*  |  None | -85  |    44   |   WPA2 Personal    |
|   9    |      *CENSORED*       |  None | -76  |    1    |   WPA2 Personal    |
|   10   |   *CENSORED*   |  None | -83  |    6    |   WPA2 Personal    |
|   11   |        *CENSORED*         |  None | -73  |    4    |   WPA2 Personal    |
|   12   | *CENSORED* |  None | -91  |    11   |   WPA2 Personal    |
|   13   |        *CENSORED*         |  None | -80  |    6    |        WEP         |
|   14   |      *CENSORED*      |  None | -78  |    6    |        Open        |
|   15   |     *CENSORED*     |  None | -80  |    6    |   WPA2 Personal    |
+--------+----------------------+-------+------+---------+--------------------+

Select a network to crack: 3

Initiating zizzania to capture handshake...

Traceback (most recent call last):
  File "/Users/*CENSORED*/Downloads/wifi-cracking-macos/WiFiCrackPy/WiFiCrackPy.py", line 142, in <module>
    scan_networks()
  File "/Users/*CENSORED*/Downloads/wifi-cracking-macos/WiFiCrackPy/WiFiCrackPy.py", line 83, in scan_networks
    capture_network(networks[x]['bssid'], networks[x]['channel'])
  File "/Users/*CENSORED*/Downloads/wifi-cracking-macos/WiFiCrackPy/WiFiCrackPy.py", line 104, in capture_network
    subprocess.run(['sudo', zizzania_path, '-i', iface, '-b', bssid, '-w', 'capture.pcap', '-q'] + ['-n'] * args.d)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any idea what the issue could be here? 

Edit: Okay just realized it's not getting the BSSIDs so uh...hehe

**Comment by IhorMuliar** [comment]
Hey. How did you fix this problem?
