### ISSUE TITLE
Mac os Monterey issue

### ISSUE THREAD

**Issue by Kekingers** [phenotypic/WiFiCrackPy#24]
hi i run into this issue when try to crack wifi
Traceback (most recent call last):
  File "/Users/h4tr3d/WiFiCrackPy/WiFiCrackPy/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/h4tr3d/WiFiCrackPy/WiFiCrackPy/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/h4tr3d/WiFiCrackPy/WiFiCrackPy/WiFiCrackPy/WiFiCrackPy.py", line 118, in capture_network
    subprocess.run(['sudo', zizzania_path, '-i', iface, '-b', bssid, '-w', 'capture.pcap', '-q'] + ['-n'] * args.d)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1885, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

any suggestion how i can solve it ??

im on mac os Monterey 12.7.4 mac book air 13" early 2015

TY

**Comment by phenotypic** [comment]
For CoreWLAN-related bugs, please refer to issue #19.

Ensure Python has been granted Location Services permissions by going to `System Settings` > `Privacy & Security` > `Location Services` and checking next to `Python`.
