### ISSUE TITLE
Crash on Macbook Air M2

### ISSUE THREAD

**Issue by Carbone13** [phenotypic/WiFiCrackPy#25]
Crash most of the time when capturing a handshake :
```shell
+] Waiting for traffic, press Ctrl-C to exit...
^C[+] Terminating...
Traceback (most recent call last):
  File "/Users/lucas/dev/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/lucas/dev/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/lucas/dev/WiFiCrackPy/WiFiCrackPy.py", line 118, in capture_network
    subprocess.run(['sudo', zizzania_path, '-i', iface, '-b', bssid, '-w', 'capture.pcap', '-q'] + ['-n'] * args.d)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1201, in communicate
    self.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It actually worked several time, and captured a correct handshake, yet most of the time hashcat can't find the password, as if the data was kind of damaged. This second issue is certainly not related to the first one though.

I have zero idea of what causes these crashes; and nothing seems to explain why it sometime works

**Comment by phenotypic** [comment]
Hi there, it appears you are terminating the script with `Ctrl-C`: `^C[+] Terminating...`
