### ISSUE TITLE
Error `TypeError: expected str, bytes or os.PathLike object, not NoneType` on selecting network to crack zizzania handshake

### ISSUE THREAD

**Issue by 1mehdifaraji** [phenotypic/WiFiCrackPy#28]
After selecting the network to crach, it throws the error `TypeError: expected str, bytes or os.PathLike object, not NoneType`.

Mac M1 Ventura `13.3.1`.

![Screenshot 1403-05-04 at 23 37 57](https://github.com/user-attachments/assets/bf1dde3a-9d4e-4935-800d-4ded35a7871d)

![Screenshot 1403-05-04 at 23 38 06](https://github.com/user-attachments/assets/040f4ede-8417-450b-87cd-68c6ea96f60a)

**Comment by phenotypic** [comment]
For CoreWLAN-related bugs, please refer to issue #19.

If you receive the `Unable to obtain authorisation, exiting...` error, ensure Python has been granted Location Services permissions by going to `System Settings` > `Privacy & Security` > `Location Services` and checking next to `Python`.

**Comment by 1mehdifaraji** [comment]
@phenotypic 

I don't think it's a location permission issue, can you confirm it by the logs below?

![Screenshot 1403-05-05 at 02 00 10](https://github.com/user-attachments/assets/1be15511-7300-42dd-9269-430c455d3778)

![Screenshot 1403-05-05 at 02 01 26](https://github.com/user-attachments/assets/c9c59726-76b7-4492-99ef-ea4d8865d5c7)

```
Initiating zizzania to capture handshake...

Traceback (most recent call last):
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 118, in capture_network
    subprocess.run(['sudo', zizzania_path, '-i', iface, '-b', bssid, '-w', 'capture.pcap', '-q'] + ['-n'] * args.d)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by 1mehdifaraji** [comment]
It turns out python version `3.9.6` won't get `BSSID` of the networks so I did install version `3.9.13` and for some reason it worked and now it reveals the `BSSID` of networks. However now I get the error `FileNotFoundError: [Errno 2] No such file or directory: 'hcxpcapngtool'`

Full error log

```
Select a network to crack: 2

Initiating zizzania to capture handshake...

sudo: /Users/mehdi/zizzania/src/zizzania: command not found
Traceback (most recent call last):
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 121, in capture_network
    subprocess.run(['hcxpcapngtool', '-o', 'capture.hc22000', 'capture.pcap'], stdout=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hcxpcapngtool'
```
