### ISSUE TITLE
wificrackpy Mac OS  issue with hash file

### ISSUE THREAD

**Issue by lex554** [phenotypic/WiFiCrackPy#40]
bit of a noob ,I'm using Mac Pro sequoia testing my network, Im getting 4 way handshake no problem but then getting this every time no matter if I use brute force dictionary act

Input a brute-force pattern: hashcat -m 22000 hashfile.22000 -a 3 "?u?u?d?u?u?d?d?u"
Traceback (most recent call last):
  File "/Users/macbookpro2020/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/macbookpro2020/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/macbookpro2020/WiFiCrackPy/WiFiCrackPy.py", line 125, in capture_network
    crack_capture()
  File "/Users/macbookpro2020/WiFiCrackPy/WiFiCrackPy.py", line 154, in crack_capture
    subprocess.run([hashcat_path, '-m', '22000', '-a', '3', 'capture.hc22000', pattern] + ['-O'] * args.o)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/macbookpro2020/hashcat/hashcat'
macbookpro2020@Macbooks-MacBook-Pro WiFiCrackPy %

**Comment by phenotypic** [comment]
Hi there, you need to provide a recognised [brute-force pattern](https://hashcat.net/wiki/doku.php?id=mask_attack).

For example, `?l?l?l`.
